CREATE TABLE IF NOT EXISTS users (
    ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    DOCUMENT BIGINT UNIQUE,
    EMAIL VARCHAR(100) UNIQUE,
    PASSWORD VARCHAR(100),
    BALANCE DECIMAL(10, 2),
    USER_TYPE VARCHAR(20)
);

CREATE UNIQUE INDEX IF NOT EXISTS document_idx on users (document);
CREATE UNIQUE INDEX IF NOT EXISTS email_idx on users (email);

CREATE TABLE IF NOT EXISTS transactions (
    ID SERIAL PRIMARY KEY,
    RECEIVER_ID INT,
    SENDER_ID INT,
    AMOUNT DECIMAL(10, 2),
    CREATED_AT TIMESTAMP,
    FOREIGN KEY (RECEIVER_ID) REFERENCES users (ID),
    FOREIGN KEY (SENDER_ID) REFERENCES users (ID)
);
